//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANALISIS
    {
        public int IdAnalisis { get; set; }
        public string IdPersona { get; set; }
        public int NivelDeRiesgoGenerado { get; set; }
        public int TotalDePalabrasClaveEncontradas { get; set; }
        public int CantidadDeArchivosEmparejados { get; set; }
        public System.DateTime FechaDeAnalisis { get; set; }
        public string Comentario { get; set; }
    }
}
