//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrega
    {
        public int EntregaId { get; set; }
        public int VentaId { get; set; }
        public string DireccionEntrega { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaProgramada { get; set; }
        public Nullable<System.DateTime> FechaEntregado { get; set; }
        public string Observacion { get; set; }
    
        public virtual Venta Venta { get; set; }
    }
}
