//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABITACIONES
    {
        public int ID { get; set; }
        public string CODIGO_DE_HABITACION { get; set; }
        public string NOMBRE_DE_HABITACION { get; set; }
        public int CANTIDAD_DE_HUESPEDES_PERMITIDOS { get; set; }
        public int CANTIDAD_DE_CAMAS { get; set; }
        public int CANTIDAD_DE_BANOS { get; set; }
        public string UBICACION { get; set; }
        public string ENCARGADO_DE_LIMPIEZA { get; set; }
        public int TIPO_DE_HABITACION { get; set; }
        public decimal COSTO_DE_LIMPIEZA { get; set; }
        public decimal COSTO_DE_RESERVA { get; set; }
        public System.DateTime FECHA_DE_REGISTRO { get; set; }
        public Nullable<System.DateTime> FECHA_DE_MODIFICACION { get; set; }
        public Nullable<bool> ESTADO { get; set; }
    }
}
