//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int PagoId { get; set; }
        public int FacturaId { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal Monto { get; set; }
        public string Metodo { get; set; }
        public string Referencia { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
