//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PALABRAS_CLAVE
    {
        public int IdPalabra { get; set; }
        public string Palabra { get; set; }
        public int Orden { get; set; }
        public System.DateTime FechaDeRegistro { get; set; }
        public Nullable<System.DateTime> FechaDeModificacion { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
