//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFacturasCompra
    {
        public int FacturaCompraID { get; set; }
        public int OrdenCompraID { get; set; }
        public int ProveedorID { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public decimal MontoTotal { get; set; }
        public decimal MontoPagado { get; set; }
        public string Estado { get; set; }
    
        public virtual tbOrdenesCompra tbOrdenesCompra { get; set; }
        public virtual tbProveedores tbProveedores { get; set; }
    }
}
