//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbOrdenesCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbOrdenesCompra()
        {
            this.tbDetalleOrdenCompra = new HashSet<tbDetalleOrdenCompra>();
        }
    
        public int OrdenCompraID { get; set; }
        public int ProveedorID { get; set; }
        public System.DateTime FechaOrden { get; set; }
        public decimal Total { get; set; }
        public bool Estado { get; set; }
        public string EstadoRecepcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetalleOrdenCompra> tbDetalleOrdenCompra { get; set; }
    }
}
