//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProductos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbProductos()
        {
            this.tbDetalleCompra = new HashSet<tbDetalleCompra>();
            this.tbDetalleCotizacion = new HashSet<tbDetalleCotizacion>();
            this.tbDetalleOrdenCompra = new HashSet<tbDetalleOrdenCompra>();
        }
    
        public int ProductoID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int Stock { get; set; }
        public decimal Precio { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> CategoriaID { get; set; }
        public int ProveedorID { get; set; }
        public bool Estado { get; set; }
        public string ImagenEjemplo { get; set; }
    
        public virtual tbCategorias tbCategorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetalleCompra> tbDetalleCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetalleCotizacion> tbDetalleCotizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDetalleOrdenCompra> tbDetalleOrdenCompra { get; set; }
        public virtual tbProveedores tbProveedores { get; set; }
    }
}
