//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProductos
    {
        public int ProductoID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int Stock { get; set; }
        public decimal Precio { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> CategoriaID { get; set; }
        public int ProveedorID { get; set; }
    
        public virtual tbCategorias tbCategorias { get; set; }
        public virtual tbProveedores tbProveedores { get; set; }
    }
}
